= So, who's Joseph?
:hp-tags: personal, bio, contact

I'm an *IT professional* living in *San Francisco*. For the most part, this blog will center around my beginnings in cybersecurity, with a focus in reversing and packet analysis.

My fascination for hacker culture came at a young age when words like _phreak_, _cracker_, and _leet_ were still relevant to the underground colloquial. It's hard to believe that in a decade, _hacking_, a term once abused by media to describe the delinquent activities of cyberpunks, had matured into the socially integrated practice we know it as today. But I couldn't imagine an advanced civilization without its natural counterpart, the breakers. I mean that besides its rise into academia and mainstream cinema, hacking is now a fundamental tool for survival. _Cybercrime_, _cyberwarfare_, _cyberterrorism_...it was indeed by necessity that I would find my purpose in cybersecurity.

Ping me at *pyxozjhi@protonmail.com* or *+14153356746*

### Nota bene

My study material is primarily security-related. For those who'd be interested, I made some of those feeds available for you to peruse.

* https://feedly.com/pyxozjhi[Feedly]
* http://sharedli.st/pyxozjhi[Pocket]
* https://open.spotify.com/user/pyxozjhi[Spotify]
* https://www.youtube.com/channel/UCM91hogdx5-YaC6x0KY5Bjw/playlists?view=52&sort=dd[YouTube]
