= Who is Joseph?
:hp-tags: personal, bio

I'm an *IT professional* living in *San Francisco*. For the time being, these notes will center around my newfound venture into reversing and packet analysis.

My passion for hacking came at a young age when "2600", "Warez" and "Sub7" were still relevant buzzwords in the computing underground. To no surprise, what once was believed to be a disagreeable practice carried out by cyberpunks, would eventually find its acceptance by our culture as an academic and socially integrated study. Albeit late, it was not until my purpose came to fruition, that I would intimately pursue what we know today as _cybersecurity_.

### Nota bene

My study material is primarily security-related. For those who might be interested, I made some collections available for you to peruse.

* link::https://feedly.com/pyxozjhi[Feedly]
* link::http://sharedli.st/pyxozjhi[Pocket]
* link::open.spotify.com/user/pyxozjhi[Spotify]
* link::https://www.youtube.com/channel/UCM91hogdx5-YaC6x0KY5Bjw/playlists?view=52&sort=dd[YouTube]