= Who is this Joseph?
:hp-tags: personal, bio, contact

I'm an *IT professional* living in *San Francisco*. For the time being, this blog will center around my beginnings in reverse engineering and packet analysis.

My fascination for hacking came at a young age when IRC, 2600, Sub7 and were still relevant amongst in the internet underground. To no surprise, what once was believed to be a delinquent act carried out by cyberpunks would eventually find its acceptance by our culture, not only as a necessity, but also as an academic and socially integrated practice. And as the space further evolved into this rich and complex admixture of disciplines, it became an imperative for me to get more involved. Once my purpose came to fruition, I embarked upon a journey to finally pursue what is known today as _cybersecurity_.

Ping me at pyxozjhi@protonmail.com

### Nota bene

My study material is primarily security-related. For those who'd be interested, I made some of those feeds available for you to peruse.

* https://feedly.com/pyxozjhi[Feedly]
* http://sharedli.st/pyxozjhi[Pocket]
* https://open.spotify.com/user/pyxozjhi[Spotify]
* https://www.youtube.com/channel/UCM91hogdx5-YaC6x0KY5Bjw/playlists?view=52&sort=dd[YouTube]
