= So, who's Joseph?
:hp-tags: personal, bio, contact

I'm an *IT professional* living in *San Francisco*. This blog will center mostly around my beginnings in cybersecurity, with a focus in reversing and packet analysis.

My fascination for hacker culture came at a young age when words like _phreak_, _cracker_, and _leet_ were still relevant  to the underground colloquial. In the past decade, _hacking_, a term once abused by media to describe the delinquent activities of cyberpunks, eventually matured into the civilized and socially integrated practice we know today. Not only has it evolved into an academic discipline but, more importantly, it became a tool fundamental to our survival. Cyberterrorism, cyberwarfare, cybercrime...it is by necessity that cybersecurity became my latest endeavor.

Ping me at *pyxozjhi@protonmail.com* or *+14153356746*

### Nota bene

My study material is primarily security-related. For those who'd be interested, I made some of those feeds available for you to peruse.

* https://feedly.com/pyxozjhi[Feedly]
* http://sharedli.st/pyxozjhi[Pocket]
* https://open.spotify.com/user/pyxozjhi[Spotify]
* https://www.youtube.com/channel/UCM91hogdx5-YaC6x0KY5Bjw/playlists?view=52&sort=dd[YouTube]
